workflows:
  my-workflow:
    name: My workflow name
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      vars:             # Define your environment variables here
        ncovSandboxKey: Encrypted(Z0FBQUFBQmdwbmlFN1pkb2t2cTBuWFhpZzBqNzhkRDNGdzM4OE9Ya0hZaWZ0dmFwUlBjRGlySGJSMVQ3ZWpMbFNMampTVVBvVGlkZWVrdzZ0ZVJER2MzdEdXdzdGRXg0YThpRHpPd3F5OGFkaVJDUnFPampsQ1dsNHZSMzZ4X1hIX0dzTGk5S3R6M1RkZnZiTjlMRnhGelVSMHlCU2dJb0tVN3F0RGZCcExwY2dJWE5iWktHRXhSQXdvYVVHeUdjRFl4UGdRR0drbVJ3d2ZYeHRLSnFfNEtxdFlGbVFPckpWNkdjT3RRcVRyTzRtaGkyemZnV1QwRlYyQUJ2ZXU5ZTFPWmJhZmhmekdpVDJGT3phTWlVazR3a3V3ZFE5bDFLZllha0hSaDJqdDNVS2VtcG93ZkMzNkV2MjEzQXlvTVM1V0J5eTdqYm1XV2plZVpvbFhLM2xVN1ZyVWRIYU44VDhpMXhwTmJ3RVFvd1I2R2NmQ1RtaS1jUDBDOXB4WmJpc3VpZG9fVGsyX2sxMV85Szd6bm42UEg2RzAwdEpuQWxQZlgydmx4X1hlclg0NExQdm1Jbl91YkhqNjhKVGlweGtZM1pXRDVpWDRld19iZF80YndNbW9SalFQRmYtZUVXZU1YWW0wSFliUmtaN0hYTE8tRDhSbUVBSlAxMDNwT2k5MjVuYkR5RUxGOTJlR2N1STMwLWdHOTl5NXRiMnpmX0N5WE1MTW5QM2oxdzQ0QUxrbGEwTEZvOUxPXzQ2cmxfMjMwRjhZNDQ0eEYyaEx6UkJZSFR3bWNFSE45TUo1MVlRRGQxcHM5X0VJbEJnOXgxR09WSmxMeVNmQjFxbXpuSExtS0FQR3NMRW1HUFpxUkIyR0NsVDdUbm4zQ09yaDVwYXcwQm9wb3drRHlPOFZSck95NnBsYk9vMXJwYjhNVEFBejRTN0NTSi1kNGtWMHRaMURIUnIzcXkzaEptN1AtZ1BHa2FQWkxVOF9LaExMUEZLWDJ2RS16bWRLMHhMemNLQ0M4cW11TlFYSDk5bllKV1RYdUdpUmpOX3otd3pZZVVzQjBxVTN4UkF4cG9KdDVKZDB2S3NOV3AyYUdaclUydERBZ0lqcVVPbmhxeXFETGZjTUQtWlpZMjYxM1U0V21jRXAwNFhjLVF3elN4WEh6YWIwdElMMzJWRHhNeGhoZDdGNmF1c0xPQXR1SU5GZi0ybl9tUW5Wc0FtMUl2U0hkNEF6Y0hXdVp6X0EtamFZTTIyak9rRS1ERTRXYkJMeUlKSnJkZDVISEt6LTcxTndmV1NvMDVMUUhXWm5WX29uNjhETnU0cjFwbk1ucTNfQUV6dkZUM3UyUGtua3lUaEtUM2R1ejVWdUhEaVBLeERQLU9aMnFHODFqWHF2bWpPN0pwczctRk83d1hXZXZtZm1JandUZmpOT3JYMUNUSnRWZWRwTHI1ZlFESWRXUVdXS0RnM0hGWEFhMGxXcm44MG9aaXVCNWEyQkExYmpQVEdqMEQ3dHNYWU1FU3RsbmpxczBSVG1ya2xkY1JGUU1ZeHQ5SHI4QnJudktpLUVBOTVLUnpNZGdrTld6dFNaM0x5UkxLLTNLeW9ZbnhLcXROWmE0ckV4OF9sbFozclpsTzA1S1dnRjRwOWNzMUxqeERvS3R2dUhfenh4dV83WnVOS2lxVXFDU2xaNHlBcWRYTmVnTVZhZFpQQVUyQ1pXSGNsTHpZd2U3dU5VeFI5RzF3RmFqVm1udDlrMXdFTm9oMWlYclJ2Y1R5Sld0UEhrNERSSE1HVk5hLTJCM0NOOWVPTHZXd1AwMWJyUy00ejBlXzV3b3lzQVBwMHIyaHpQdHIwd1ZCS1ZrdkhwSXVlcTNVZ1lpcjh3MEJqU2sxT3RtV3BTaWRxSTJaUnc1a3BCekZJVjhUb2c9PQ==)
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - ...
    artifacts:
      - build/**/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - testerkagiso@gmail.com
      scripts:
        - echo 'Post-publish script'
